# Generated by Django 3.0.6 on 2020-07-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_vanilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('nutriscore', models.CharField(max_length=1)),
                ('image_url', models.URLField()),
                ('category', models.CharField(default='UNKNOW', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product_saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_requested', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='datadisp.Product_vanilla')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.User')),
            ],
        ),
    ]
