# Generated by Django 3.0.6 on 2020-07-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadisp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_vanilla',
            name='carbohydrates',
            field=models.CharField(default='UNKNOW', max_length=255),
        ),
        migrations.AddField(
            model_name='product_vanilla',
            name='energy',
            field=models.CharField(default='UNKNOW', max_length=255),
        ),
        migrations.AddField(
            model_name='product_vanilla',
            name='energy_kcal',
            field=models.CharField(default='UNKNOW', max_length=255),
        ),
        migrations.AddField(
            model_name='product_vanilla',
            name='fat',
            field=models.CharField(default='UNKNOW', max_length=255),
        ),
        migrations.AddField(
            model_name='product_vanilla',
            name='protein',
            field=models.CharField(default='UNKNOW', max_length=255),
        ),
        migrations.AddField(
            model_name='product_vanilla',
            name='salt',
            field=models.CharField(default='UNKNOW', max_length=255),
        ),
        migrations.AddField(
            model_name='product_vanilla',
            name='saturated_fat',
            field=models.CharField(default='UNKNOW', max_length=255),
        ),
        migrations.AddField(
            model_name='product_vanilla',
            name='sugar',
            field=models.CharField(default='UNKNOW', max_length=255),
        ),
    ]
