# Generated by Django 3.0.6 on 2020-07-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadisp', '0002_auto_20200726_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_vanilla',
            name='url',
            field=models.URLField(default='UNKNOW'),
        ),
    ]
